### ISSUE TITLE
Getting it.alfrescoinaction.lab.awsi.exceptions.ObjectNotFoundException

### ISSUE THREAD

**Issue by p4535992** [david-ciamberlano/website-inventor#4]
Hi sorry to bother, maybe i just make something wrong with the configuration:
I built the war and put in a apache tomcat , make it running on the port 8585, the deploy is fine, after i check out the default site of alfresco on the address:
http://localhost:8080/share/page/site/swsdp/dashboard 
and the cmis service entry url, is running all fine, but when i go to chekout the url:
 http://localhost:8585/alfresco-website-inventor-1.0-SNAPSHOT/swsdp/page/home 

 i get the text "Error it.alfrescoinaction.lab.awsi.exceptions.ObjectNotFoundException"

here my aiws configuration:
../apache/tomcat/conf/aiws.properties
```
#Connection to Alfresco
alfresco.username=admin
alfresco.password=xxxxxxxxxxxxx
alfresco.serverProtocol=http
alfresco.serverUrl=localhost:8080
alfresco.cmisEntryPoint=/alfresco/api/-default-/public/cmis/versions/1.1/browser
alfresco.serviceEntryPoint=/alfresco/s
```
../apache/tomcat/conf/.awsi.config
```
{
  "enable-websiteinventory": true,
  "siteName": "Nome Sito",
  "theme": "default",
  "metadata": [
	{"label":"Name", "propertyId":"name", "type":"TEXT"},
	{"label":"Title", "propertyId":"title", "type":"TEXT"},
	{"label":"Creator", "propertyId":"createdBy", "type":"TEXT"},
	{"label":"Creation date", "propertyId":"creationDate", "type":"DATE"}
  ]
}
```

I make something wrong with the configuration?

**Comment by david-ciamberlano** [comment]
Hi,
sorry, its my fault! 

The _".awsi.config"_ file must be copied in the Alfresco repository.
For example: for the "swsdp" site you must copy that file in the "repository>sites>swsdp" folder (at the same level of the "documentLibrary" folder).

If you have other questions I will be happy to answer them.

**Comment by p4535992** [comment]
ty work like charm, a very good projet for start a customize application to interact with the alfresco machine.
